repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
  - repo: local
    hooks:
      - id: npm-check
        name: npm run check
        entry: npm run check
        language: system
        pass_filenames: false
